< ../config.mk

all:QV:
	bin/targets | xargs mk

results/%.chrM.fastq:Q: data/SNAP_bams/%.bam
	mkdir -p $(dirname $target)
	echo "[DEBUGGING]doing $target"
	samtools view -h -F 4 $prereq \
	| grep -e "chrM__" -e "^@" \
	| samtools view -S -b - \
	| bamToFastq -i - -fq $target.build \
	&& mv $target.build $target

results/%.unmapped.fastq:Q: data/SNAP_bams/%.bam
	mkdir -p $(dirname $target)
	echo "[DEBUGGING]doing $target"
	samtools view -h -f 4 -b $prereq \
	| bamToFastq -i - -fq $target.build \
	&& mv $target.build $target

results/formito_%.fastq.gz:Q: results/%.chrM.fastq results/%.unmapped.fastq
	mkdir -p $(dirname $target)
	echo "[DEBUGGING]doing fastq convertion to $target"
	cat $prereq | gzip -f -9 > $target.build \
	&& mv $target.build $target
